build_image:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login registry.gitlab.com -u tclavier -p $DOCKER_TOKEN
    - docker build -t registry.gitlab.com/azae/azae.net .
    - docker push registry.gitlab.com/azae/azae.net

deploy:
  script:
    - curl -X POST -data=""  https://deliverous.com/api/v1/trigger/$DELIVEROUS_TRIGGER
