# Site settings
baseline: Catalyseur d'agilité
keywords:
- Devops
- Agile
- Scrum
- Formation
- Linux
- Opensource
- Puppet
- Chef
- Architecture web
- Cloud
- Lille
- Roubaix
- Tourcoing
- Villeneuve d'ascq

url: "http://azae.net"
baseurl: ""


defaults:
- scope:
    path: "articles"
    type: "posts"
  values:
    permalink: /articles/:title.html
    layout: article


markdown: kramdown


gems:
- jekyll-paginate


exclude:
- README.md
- Dockerfile
- Gemfile
