# Site settings
title: Azaé
baseline: Catalyseur d'agilité

url: "http://azae.net"
baseurl: ""


markdown: kramdown


gems:
- jekyll-paginate


defaults:
- scope:
    path: "articles"
    type: "posts"
  values:
    permalink: /articles/:title.html
    layout: article


exclude:
- README.md
- Dockerfile
- Gemfile
