#!/bin/bash
if [ -z $http_proxy ]
then
  BUILD_OPTS=""
else
  [ "$http_proxy" == "http://localhost:8123" ] && PROXY="http://172.17.0.1:8123/" || PROXY="$http_proxy"
  BUILD_OPTS="--build-arg http_proxy=$PROXY"
fi

docker build --pull $BUILD_OPTS -t jekyll .
docker run -v $(pwd):/workspace -it -p 4000:4000 jekyll jekyll serve --watch --drafts --destination /var/www --host 0.0.0.0
